### PYTHON LİSTE

In [2]:
#Numpy dizileri oluşturma

In [12]:
import numpy as np

In [22]:
veri1 = np.arange(6) #0'dan 5'e kadar

In [24]:
veri1

array([0, 1, 2, 3, 4, 5])

In [26]:
print(veri1) #veriyi yazdırma

[0 1 2 3 4 5]


In [30]:
print(veri1.shape) #verinin büyüklüğünü gösterme

(6,)


In [34]:
veri2= np.arange(10,22,3)#10'dan 22'ye kadar 3'er artırımlı veri
print(veri2)

[10 13 16 19]


In [36]:
veri3=np.zeros(6) # tüm değerleri sıfır olan dizi
print(veri3)
print(veri3.shape)

[0. 0. 0. 0. 0. 0.]
(6,)


In [38]:
veri4=np.zeros((3,4)) # tüm değerleri sıfır olan 3x4 matrisi
print(veri4)
print(veri4.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [40]:
veri5=np.full((3,4),5) # tüm değerleri beş olan 3x4 matrisi
print(veri5)
print(veri5.shape)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)


In [42]:
veri6=np.eye(5) #5x5 birim matrisi
print(veri6)
print(veri6.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


In [44]:
veri7=np.random.random((3,4)) #[0,1) yarı açık aralığından 
print(veri7)
print(veri7.shape)

[[0.97819195 0.77473528 0.30428441 0.370976  ]
 [0.14184445 0.40189219 0.23059932 0.24181626]
 [0.16083661 0.03384535 0.96935366 0.8400304 ]]
(3, 4)


In [46]:
liste1=[12,22,14,15,16] # Bir pyhton listesinden bir Numpy dizisi oluşturma
a1=np.array(liste1)
print(a1)

[12 22 14 15 16]


In [54]:
print(a1[0]) #dizinin 1. elemanını yazdır
print(a1[1])
print(a1[4])

12
22
16


In [58]:
liste1=[12,22,14,15,16]
liste2=[102,212,141,315,716]
a2=np.array([liste1,liste2]) # iki diziyi sıralama
print(a2)

[[ 12  22  14  15  16]
 [102 212 141 315 716]]


In [78]:
sayılar=np.arange(15)
print(sayılar)
çift_sayılar=sayılar[sayılar%2==0] # 2'ye bölümünden kalan 0 olan sayılar
print(çift_sayılar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]


In [86]:
a3=np.array([[11,21,33,43,75],[4,5,61,17,8],[19,8,77,6,51]])
print(a3)

[[11 21 33 43 75]
 [ 4  5 61 17  8]
 [19  8 77  6 51]]


In [88]:
print("    ")
b3=a3[0:3,:3] #ilk üç satırı ve ilk üç sütunu al
print(b3)

    
[[11 21 33]
 [ 4  5 61]
 [19  8 77]]


In [92]:
import numpy as np
x1=np.array([2,3,5])
x2=np.array([7,4,2])
np.dot(x1,x2) # iç skaler çarpımı:2x7+3x4+5x2

36

In [98]:
m1=np.array([[11,21,3],[21,4,5]])
m2=np.array([[7,8],[9,10],[11,12]])
print(m1)
print(m2)

print(np.dot(m1,m2)) #matris çarpımı

[[11 21  3]
 [21  4  5]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[299 334]
 [238 268]]


In [100]:
m3=np.array([(11,22,33,44),(4,5,6,7),(27,28,29,30)])
print(m3)
print(m3.cumsum()) #kümülatif toplamlarıbir dizi halinde yazma

[[11 22 33 44]
 [ 4  5  6  7]
 [27 28 29 30]]
[ 11  33  66 110 114 119 125 132 159 187 216 246]


In [102]:
yaşlar=np.array([44,22,37,56,13,77,61])
sıralanmış_yaşlar=np.sort(yaşlar) # ya da yaşlar.sort
print(yaşlar)
print(sıralanmış_yaşlar)

[44 22 37 56 13 77 61]
[13 22 37 44 56 61 77]


In [114]:
kardeşler=np.array(["Recep","Fatma","Şaban","Emine","Selvi"])
yaş=np.array([60,57,55,51,49])
boy=np.array([188,165,190,169,170])

In [118]:
diz=np.argsort(yaş)
diz1=np.argsort(boy)
print(kardeşler[diz])
print(kardeşler[diz1])

['Selvi' 'Emine' 'Şaban' 'Fatma' 'Recep']
['Fatma' 'Emine' 'Selvi' 'Recep' 'Şaban']


In [120]:
ters_diz=np.argsort(kardeşler)[::-1] # büyüklüğüne ya da alfabetik olarak tersine sıralama
print(yaş[ters_diz])
print(boy[ters_diz])

[55 49 60 57 51]
[190 170 188 165 169]


In [124]:
liste1=[[15,25,34,47],[54,64,75,85],[154,164,715,825]]
d1=np.array(liste1)
print(d1)

[[ 15  25  34  47]
 [ 54  64  75  85]
 [154 164 715 825]]


In [126]:
d2=d1
print(d2)

[[ 15  25  34  47]
 [ 54  64  75  85]
 [154 164 715 825]]


In [128]:
d2[0][0]=999 # d2 matrisinin 1. satır ve 1. sütun elemanını 999 olarak değştirme
print(d2)

[[999  25  34  47]
 [ 54  64  75  85]
 [154 164 715 825]]


In [130]:
d2[1][3]=-888 #d2 matrisinin 2. satır 4. sütun elemanını -888 olarak değiştirme
print(d2)

[[ 999   25   34   47]
 [  54   64   75 -888]
 [ 154  164  715  825]]


In [132]:
d2.shape=2,-1 # 3x3 boyutundaki d2 matrisi 2 satıra indirgeme
print(d2)

[[ 999   25   34   47   54   64]
 [  75 -888  154  164  715  825]]


Pandas Serileri

In [135]:
import pandas as pd

In [137]:
df=pd.DataFrame({
    "İsim":["Melih","Kübra","Büşra","Kürşat","Gülnur","Feyzi","Esra","Zişan","Mustafa","Zeynep","Hayrunnisa"],
    "Yaş":[37,36,33,29,27,25,25,20,19,16,14],
    "Cinsiyet":["erkek","kadın","kadın","erkek","kadın","erkek","kadın","kadın","erkek","kadın","kadın"]}
               )


In [139]:
df

İsim  Yaş Cinsiyet
0        Melih   37    erkek
1        Kübra   36    kadın
2        Büşra   33    kadın
3       Kürşat   29    erkek
4       Gülnur   27    kadın
5        Feyzi   25    erkek
6         Esra   25    kadın
7        Zişan   20    kadın
8      Mustafa   19    erkek
9       Zeynep   16    kadın
10  Hayrunnisa   14    kadın

In [141]:
df["Cinsiyet"]

0     erkek
1     kadın
2     kadın
3     erkek
4     kadın
5     erkek
6     kadın
7     kadın
8     erkek
9     kadın
10    kadın
Name: Cinsiyet, dtype: object

In [143]:
df["Yaş"].max() # veya

37

In [157]:
yaş.max()

60

In [159]:
Yaş=pd.Series([37,36,33,29,27,25,25,20,19,16,14], name="Yaş")

In [163]:
Yaş

0     37
1     36
2     33
3     29
4     27
5     25
6     25
7     20
8     19
9     16
10    14
Name: Yaş, dtype: int64

In [165]:
df.describe()

Yaş
count  11.000000
mean   25.545455
std     7.802098
min    14.000000
25%    19.500000
50%    25.000000
75%    31.000000
max    37.000000

In [175]:
veri = {"isim":["Hüsnü","Nevzat","Dr.Erol","Talat","Yüksel","Adem","İzzet"],
        "yıl":[1969,1965,1971,1971,1972,1975,1978],
        "doğum_yeri":["Çarşamba","Havza","Araklı","Karabük","Sürmene","Of","Hatay"],
        "çocuk_sayısı":[2,4,1,2,3,3,5]}
veri=pd.DataFrame(veri,index=[1,2,3,4,5,6,7])
print(veri)


      isim   yıl doğum_yeri  çocuk_sayısı
1    Hüsnü  1969   Çarşamba             2
2   Nevzat  1965      Havza             4
3  Dr.Erol  1971     Araklı             1
4    Talat  1971    Karabük             2
5   Yüksel  1972    Sürmene             3
6     Adem  1975         Of             3
7    İzzet  1978      Hatay             5


In [179]:
print(veri.drop([4,6])) # 4. ve 6. satırları kaldırma

      isim   yıl doğum_yeri  çocuk_sayısı
1    Hüsnü  1969   Çarşamba             2
2   Nevzat  1965      Havza             4
3  Dr.Erol  1971     Araklı             1
5   Yüksel  1972    Sürmene             3
7    İzzet  1978      Hatay             5


In [183]:
# veya
print(veri.drop(veri.index[[3,5]]))

      isim   yıl doğum_yeri  çocuk_sayısı
1    Hüsnü  1969   Çarşamba             2
2   Nevzat  1965      Havza             4
3  Dr.Erol  1971     Araklı             1
5   Yüksel  1972    Sürmene             3
7    İzzet  1978      Hatay             5


In [185]:
print(veri[veri.isim != "Dr.Erol"]) # Dr Erol'a ait satırı kaldırma

     isim   yıl doğum_yeri  çocuk_sayısı
1   Hüsnü  1969   Çarşamba             2
2  Nevzat  1965      Havza             4
4   Talat  1971    Karabük             2
5  Yüksel  1972    Sürmene             3
6    Adem  1975         Of             3
7   İzzet  1978      Hatay             5


In [189]:
print(veri.drop("doğum_yeri",axis=1)) # Doğum yeri sütununu kaldırma

      isim   yıl  çocuk_sayısı
1    Hüsnü  1969             2
2   Nevzat  1965             4
3  Dr.Erol  1971             1
4    Talat  1971             2
5   Yüksel  1972             3
6     Adem  1975             3
7    İzzet  1978             5


In [191]:
print(veri.drop(veri.columns[[1,3]],axis=1)) # 2 ve 4. sütunu silme

      isim doğum_yeri
1    Hüsnü   Çarşamba
2   Nevzat      Havza
3  Dr.Erol     Araklı
4    Talat    Karabük
5   Yüksel    Sürmene
6     Adem         Of
7    İzzet      Hatay


In [195]:
veri1=pd.DataFrame(
    {
    "Cinsiyet":["erkek","erkek","kadın","kadın","erkek","kadın","kadın"],
    "Takım":["GS","GS","BJK","FB","TS","TS","GS"]
    }
)
print(veri1)

  Cinsiyet Takım
0    erkek    GS
1    erkek    GS
2    kadın   BJK
3    kadın    FB
4    erkek    TS
5    kadın    TS
6    kadın    GS
